const products = [
  {
    _id: '1',
    name: 'AC Milan Home Jersey',
    image: '/images/acmilan.jpg',
    description:
      'Represent AC Milan in style with 2020/21 official team home jersey. Produced by Puma',
    brand: 'Puma',
    category: 'Jersey',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Arsenal Home Jersey',
    image: '/images/arsenal.jpg',
    description:
      'Represent Arsenal in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Adidas',
    category: 'Jersey',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Barcelona Home Jersey',
    image: '/images/barcelona.jpg',
    description:
      'Represent Barcelona in style with 2020/21 official team home jersey. Produced by Nike',
    brand: 'Nike',
    category: 'Jersey',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Bayern Munich Home Jersey',
    image: '/images/bayern.jpg',
    description:
      'Represent Bayern in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Adidas',
    category: 'Jersey',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Borussia Dortmund Home Jersey',
    image: '/images/dortmund.jpg',
    description:
      'Represent Dortmund in style with 2020/21 official team home jersey. Produced by Puma',
    brand: 'Puma',
    category: 'Jersey',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Chelsea Home Jersey',
    image: '/images/chelsea.jpg',
    description:
      'Represent Chelsea in style with 2020/21 official team home jersey. Produced by Nike',
    brand: 'Nike',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Inter Milan Home Jersey',
    image: '/images/inter.jpg',
    description:
      'Represent Inter Milan in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Nike',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Juventus Home Jersey',
    image: '/images/juve.jpg',
    description:
      'Represent Juve in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Adidas',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Liverpool Home Jersey',
    image: '/images/liverpool.jpg',
    description:
      'Represent Liverpool in style with 2020/21 official team home jersey. Produced by Nike',
    brand: 'Nike',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Manchester City Home Jersey',
    image: '/images/mancity.jpg',
    description:
      'Represent City in style with 2020/21 official team home jersey. Produced by Puma',
    brand: 'Puma',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Manchester United Home Jersey',
    image: '/images/united.jpg',
    description:
      'Represent United in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Adidas',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'PSG Home Jersey',
    image: '/images/psg.jpg',
    description:
      'Represent PSG in style with 2020/21 official team home jersey. Produced by Nike',
    brand: 'Nike',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Real Madrid Home Jersey',
    image: '/images/real.jpg',
    description:
      'Represent Real Madrid in style with 2020/21 official team home jersey. Produced by Adidas',
    brand: 'Adidas',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Tottenham Hotspur Home Jersey',
    image: '/images/tottenham.jpg',
    description:
      'Represent Tottenham in style with 2020/21 official team home jersey. Produced by Nike',
    brand: 'Nike',
    category: 'Jersey',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
